name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt update
    - name: upgrade
      run: sudo apt upgrade -y
    - name: container extra packets
      run: sudo apt install -y gcc-10 curl libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
    - name: get doctest.h
      run: curl https://raw.githubusercontent.com/onqtam/doctest/v2.4.9/doctest/doctest.h > doctest.h
    - name: pwd
      run: pwd
    - name: create build dir
      run: mkdir ../build
    - run: cd ../build
    - name: sft install
      run: git clone https://github.com/Soldy/sft.git
      run: cd sft/confs
      run: sudo cp -r usr/ /
      run: cd ../..
    - name: cmake config
      run: cmake ../screen_saver
    - name: cmake build
      run: cmake --build .
    - name: get version
      run: g++ -v
