name: GCC CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt update
    - name: upgrade
      run: sudo apt upgrade -y
    - name: configure
      run: sudo apt install -y gcc-10 curl
    - name: container extra packets
      run: sudo apt install -y libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
    - name: update submodules
      run: git submodule update --init
    - name: get doctest.h
      run: curl https://raw.githubusercontent.com/onqtam/doctest/v2.4.9/doctest/doctest.h > doctest.h
    - name: get version
      run: g++ -v
    - name: compile
      run: g++ -o test test.cpp -std=c++17 -Wall -Wextra -Iinclude -lpthread -Llib -lSDL2 -lSDL2main  -lSDL2_image
    - name: test
      run: ./test
